steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '-t'
    - 'eu.gcr.io/$PROJECT_ID/${_IMAGE_NAME}:$SHORT_SHA'
    - '-t'
    - 'eu.gcr.io/$PROJECT_ID/${_IMAGE_NAME}:latest'
    - '-f'
    - './Dockerfile'
    - './context'
  dir: docker/eu.gcr.io/$PROJECT_ID/${_IMAGE_NAME}
substitutions:
  _IMAGE_NAME: unused # Set in the trigger
  _BUILD_DIR: docker/eu.gcr.io/$PROJECT_ID/${_IMAGE_NAME}
images:
  - 'eu.gcr.io/$PROJECT_ID/${_IMAGE_NAME}:$SHORT_SHA'
  - 'eu.gcr.io/$PROJECT_ID/${_IMAGE_NAME}:latest'
options:
    substitution_option: MUST_MATCH