
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cms
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cms
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: cms.bigot.es
        tier: wordpress
    spec:
      containers:
      - image: eu.gcr.io/bigotes-pro/cms.bigot.es:3c16daf
        name: wordpress
        ports:
        - containerPort: 80
          name: wordpress
        env:
        - name: WORDPRESS_DB_HOST
          valueFrom:
            secretKeyRef:
              name: cms-db-credentials
              key: WORDPRESS_DB_HOST
        - name: WORDPRESS_DB_NAME
          valueFrom:
            secretKeyRef:
              name: cms-db-credentials
              key: WORDPRESS_DB_NAME
        - name: WORDPRESS_DB_USER
          valueFrom:
            secretKeyRef:
              name: cms-db-credentials
              key: WORDPRESS_DB_USER
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: cms-db-credentials
              key: WORDPRESS_DB_PASSWORD