
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cms-alpine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cms-alpine
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: cms-alpine
        tier: wordpress
    spec:
      hostAliases:
        - ip: "127.0.0.1"
          hostnames:
            - wordpress
      volumes:
      - name: html
        emptyDir: {}
      containers:
      - image: eu.gcr.io/bigotes-pro/cms/nginx:7081818
        name: nginx
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 200m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi
        ports:
        - containerPort: 80
          name: wordpress
        volumeMounts:
          - name: html
            mountPath: /var/www/html
      - image: eu.gcr.io/bigotes-pro/cms/wp:7081818
        name: wordpress
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 200m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi
        volumeMounts:
          - name: html
            mountPath: /var/www/html
        env:
        - name: WORDPRESS_DB_HOST
          valueFrom:
            secretKeyRef:
              name: cms-db-credentials
              key: WORDPRESS_DB_HOST
        - name: WORDPRESS_DB_NAME
          valueFrom:
            secretKeyRef:
              name: cms-db-credentials
              key: WORDPRESS_DB_NAME
        - name: WORDPRESS_DB_USER
          valueFrom:
            secretKeyRef:
              name: cms-db-credentials
              key: WORDPRESS_DB_USER
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: cms-db-credentials
              key: WORDPRESS_DB_PASSWORD
        - name: WORDPRESS_CONFIG_EXTRA
          valueFrom:
            secretKeyRef:
              name: cms-config
              key: WORDPRESS_CONFIG_EXTRA

