# For interactive prompt
SHELL = /bin/bash

# Help

help:
	@$(MAKE) -pRrq -f $(lastword $(MAKEFILE_LIST)) : 2>/dev/null \
		| awk -v RS= -F: '/^# File/,/^# Finished Make data base/ {if ($$1 !~ "^[#.]") {print $$1}}' \
		| egrep -v -e '^[^[:alnum:]]' -e '^$@$$'

# Targets

upload-bigot.es:
	gsutil rsync -R bigot.es/ gs://bigot.es
